name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install doctl for interacting with Digital Ocean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: View account details
      run: doctl account get
    - name: View account balance
      run: doctl balance get
    - name: List projects
      run: doctl projects list
    - name: List resources for do-node-file-streams-tutorial-server
      run: doctl projects resources list b76b457a-9fc8-47c0-b8ca-e25e04769dfb
